named_poses:
  leave_start_zone:
    x: 0.5
    y: 0.0
    yaw: 0.0

  stage1_entry:
    x: 1.0
    y: 0.0
    yaw: 0.0

  stage2_entry:
    x: 2.0
    y: 0.0
    yaw: 0.0

  stage3_entry:
    x: 3.0
    y: 0.0
    yaw: 0.0

  stage3_pick_pose:
    x: 3.3
    y: 0.4
    yaw: 0.0

  stage3_stack_pose:
    x: 3.7
    y: 0.4
    yaw: 0.0